#!/usr/bin/env python3
"""Build a schema-only PostgreSQL starter file from the current MariaDB dump.

The generated file deliberately omits every INSERT/data row from the source
dump. It is a schema bootstrap, not a production-data migration utility.
"""

from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "database" / "current_database.sql"
TARGET = ROOT / "database" / "postgresql_schema.sql"


def pg_type_and_column_sql(sql: str) -> str:
    sql = re.sub(r"`([^`]+)`", r'"\1"', sql)
    sql = re.sub(r"\bBIGINT\s*\(\s*\d+\s*\)\s+UNSIGNED\b", "NUMERIC(20)", sql, flags=re.I)
    sql = re.sub(r"\b(?:INT|INTEGER|MEDIUMINT|SMALLINT|TINYINT)\s*\(\s*\d+\s*\)\s+UNSIGNED\b", "BIGINT", sql, flags=re.I)
    sql = re.sub(r"\bBIGINT\s*\(\s*\d+\s*\)", "BIGINT", sql, flags=re.I)
    sql = re.sub(r"\b(?:INT|INTEGER|MEDIUMINT|SMALLINT|TINYINT)\s*\(\s*\d+\s*\)", "INTEGER", sql, flags=re.I)
    sql = re.sub(r"\bBIGINT\s+UNSIGNED\b", "NUMERIC(20)", sql, flags=re.I)
    sql = re.sub(r"\b(?:INT|INTEGER|MEDIUMINT|SMALLINT|TINYINT)\s+UNSIGNED\b", "BIGINT", sql, flags=re.I)
    sql = re.sub(r"\bTINYINT\b", "SMALLINT", sql, flags=re.I)
    sql = re.sub(r"\bMEDIUMINT\b", "INTEGER", sql, flags=re.I)
    sql = re.sub(r"\bLONGTEXT\b|\bMEDIUMTEXT\b|\bTINYTEXT\b", "TEXT", sql, flags=re.I)
    sql = re.sub(r"\bDATETIME\b", "TIMESTAMP", sql, flags=re.I)
    sql = re.sub(r"\bDOUBLE\b", "DOUBLE PRECISION", sql, flags=re.I)
    sql = re.sub(r"\bcurrent_timestamp\s*\(\s*\)", "CURRENT_TIMESTAMP", sql, flags=re.I)
    sql = re.sub(r"\bcurdate\s*\(\s*\)", "CURRENT_DATE", sql, flags=re.I)

    def enum_to_varchar(match: re.Match[str]) -> str:
        values = re.findall(r"'((?:''|[^'])*)'", match.group(1))
        width = max((len(value.replace("''", "'")) for value in values), default=1)
        return f"VARCHAR({width})"

    sql = re.sub(r"\bENUM\s*\(([^()]*)\)", enum_to_varchar, sql, flags=re.I)
    sql = re.sub(r"\s+ON\s+UPDATE\s+CURRENT_TIMESTAMP(?:\(\))?", "", sql, flags=re.I)
    sql = re.sub(r"\s+CHECK\s*\(\s*json_valid\s*\([^)]*\)\s*\)", "", sql, flags=re.I)
    sql = re.sub(r"\s+CHARACTER\s+SET\s+[a-zA-Z0-9_]+", "", sql, flags=re.I)
    sql = re.sub(r"\s+COLLATE\s+[a-zA-Z0-9_]+", "", sql, flags=re.I)
    return sql


def main() -> None:
    dump = SOURCE.read_text(encoding="utf-8")
    create_pattern = re.compile(
        r"CREATE TABLE `(?P<table>[a-zA-Z0-9_]+)`\s*\((?P<body>.*?)\)\s*ENGINE=[^;]*;",
        re.I | re.S,
    )
    creates: list[str] = []
    table_names: set[str] = set()
    auto_updated_tables: set[str] = set()
    for match in create_pattern.finditer(dump):
        table = match.group("table")
        table_names.add(table)
        raw_body = match.group("body")
        if re.search(r"\bON\s+UPDATE\s+CURRENT_TIMESTAMP", raw_body, re.I):
            auto_updated_tables.add(table)
        body = pg_type_and_column_sql(raw_body)
        body = re.sub(r",\s*\Z", "", body)
        creates.append(f'CREATE TABLE IF NOT EXISTS "{table}" ({body.strip()});')

    identities: list[str] = []
    primary_keys: list[str] = []
    indexes: list[str] = []
    foreign_keys: list[str] = []

    alter_pattern = re.compile(r"ALTER TABLE `(?P<table>[a-zA-Z0-9_]+)`(?P<body>.*?);", re.I | re.S)
    for match in alter_pattern.finditer(dump):
        table = match.group("table")
        if table not in table_names:
            continue
        body = match.group("body")

        for identity in re.finditer(
            r"MODIFY\s+`(?P<column>[a-zA-Z0-9_]+)`\s+[^,;]*?\bAUTO_INCREMENT\b",
            body,
            re.I,
        ):
            identities.append(
                f'ALTER TABLE "{table}" ALTER COLUMN "{identity.group("column")}" ADD GENERATED BY DEFAULT AS IDENTITY;'
            )

        if re.search(r"ADD\s+PRIMARY\s+KEY", body, re.I):
            cols = re.search(r"ADD\s+PRIMARY\s+KEY\s*\(([^)]*)\)", body, re.I)
            if cols:
                names = re.sub(r"`([^`]+)`", r'"\1"', cols.group(1))
                primary_keys.append(f'ALTER TABLE "{table}" ADD PRIMARY KEY ({names});')

        for key in re.finditer(
            r"ADD\s+(?P<unique>UNIQUE\s+)?(?:KEY|INDEX)\s+`(?P<name>[a-zA-Z0-9_]+)`\s*\((?P<cols>[^)]*)\)",
            body,
            re.I,
        ):
            cols = re.sub(r"`([^`]+)`", r'"\1"', key.group("cols"))
            uniqueness = "UNIQUE " if key.group("unique") else ""
            indexes.append(
                f'CREATE {uniqueness}INDEX IF NOT EXISTS "{key.group("name")}" ON "{table}" ({cols});'
            )

        for constraint in re.finditer(
            r"ADD\s+CONSTRAINT\s+`(?P<name>[a-zA-Z0-9_]+)`\s+(?P<definition>FOREIGN\s+KEY\s*\([^)]*\)\s+REFERENCES\s+`[^`]+`\s*\([^)]*\)(?:\s+ON\s+(?:DELETE|UPDATE)\s+(?:CASCADE|SET\s+NULL|RESTRICT|NO\s+ACTION))*)",
            body,
            re.I,
        ):
            definition = re.sub(r"`([^`]+)`", r'"\1"', constraint.group("definition"))
            foreign_keys.append(
                f'ALTER TABLE "{table}" ADD CONSTRAINT "{constraint.group("name")}" {definition};'
            )

    output = [
        "-- Schema-only PostgreSQL starter generated from database/current_database.sql.",
        "-- No application or user data is included. Check in sync with database migrations.",
        "",
        *creates,
        "",
        "CREATE OR REPLACE FUNCTION fas_touch_updated_at() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN NEW.updated_at := CURRENT_TIMESTAMP; RETURN NEW; END; $$;",
        *[
            f'CREATE TRIGGER "trg_uat_{table}" BEFORE UPDATE ON "{table}" FOR EACH ROW EXECUTE FUNCTION fas_touch_updated_at();'
            for table in sorted(auto_updated_tables)
        ],
        *identities,
        *primary_keys,
        *indexes,
        *foreign_keys,
        "",
    ]
    TARGET.write_text("\n".join(output), encoding="utf-8", newline="\n")
    print(f"Generated {TARGET.relative_to(ROOT)} with {len(creates)} tables and no data rows.")


if __name__ == "__main__":
    main()
